name: Call API on Repo Change

on:
  push:
    branches:
      - main  # or any branch you want

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Call DEV API endpoint
        run: |
          curl -X POST https://arche-dev.acdh-dev.oeaw.ac.at/browser/api/update-static-nodes \
            -H "Authorization: Bearer ${{ secrets.ARCHE_DRUPAL_STATICTEXT_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"message": "Update static text"}'

      - name: Call CURATION API endpoint
        run: |
          curl -X POST https://arche-curation.acdh-dev.oeaw.ac.at/browser/api/update-static-nodes \
            -H "Authorization: Bearer ${{ secrets.ARCHE_DRUPAL_STATICTEXT_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"message": "Update static text"}'      
